// gen:types (ARCHITECTURE §13, INV-14): TypeScript types from the JSON Schema `pmcc export` writes
// to public/data/schema/, one module per schema in src/types/generated/ (gitignored). A result
// model change the site doesn't handle then fails `tsc`. `version.ts` carries the schema version
// the site was built against; the loader refuses data of another (UI-SPEC §8).
//
// The schemas come from `pmcc export --schema-only` (no results needed) or a full `pmcc export`.
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { compile } from "json-schema-to-typescript";

const SCHEMA_DIR = "public/data/schema";
const OUT_DIR = "src/types/generated";
const SUFFIX = ".schema.json";
const BANNER = "// Generated by `npm run gen:types` from pmcc export's JSON Schema. Do not edit.";

// Pydantic titles every field ("Pmcc Version"), which json-schema-to-typescript turns into an alias
// per field (`type PmccVersion = string`). Only a model's title names a type; drop the rest. A
// `properties` map's keys are field names, not schema keywords: a field named `title` (a rule's,
// DEC-114) stays.
function dropFieldTitles(node, named) {
  if (Array.isArray(node)) {
    node.forEach((item) => dropFieldTitles(item, false));
  } else if (node && typeof node === "object") {
    if (!named) delete node.title;
    for (const [key, value] of Object.entries(node)) {
      if (key === "$defs") {
        Object.values(value).forEach((def) => dropFieldTitles(def, true));
      } else if (key === "properties" && value && typeof value === "object") {
        Object.values(value).forEach((field) => dropFieldTitles(field, false));
      } else {
        dropFieldTitles(value, false);
      }
    }
  }
  return node;
}

async function schemaFiles() {
  try {
    return (await readdir(SCHEMA_DIR)).filter((name) => name.endsWith(SUFFIX)).sort();
  } catch {
    return [];
  }
}

const files = await schemaFiles();
if (files.length === 0) {
  console.error(
    `No schemas in web/${SCHEMA_DIR}. Run \`uv run pmcc export --schema-only --out web/public/data\``
      + " (or `just export`) from the repo root first.",
  );
  process.exit(1);
}

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });
let version;
for (const file of files) {
  const schema = dropFieldTitles(JSON.parse(await readFile(join(SCHEMA_DIR, file), "utf8")), true);
  const name = file.slice(0, -SUFFIX.length);
  version ??= schema.properties?.schema_version?.const;
  const ts = await compile(schema, schema.title ?? name, {
    bannerComment: BANNER,
    additionalProperties: false,
    unreachableDefinitions: false,
    format: false,
  });
  await writeFile(join(OUT_DIR, `${name}.ts`), ts, { encoding: "utf8" });
}
if (typeof version !== "number") {
  console.error("The schemas carry no schema_version const; is pmcc export current?");
  process.exit(1);
}
await writeFile(
  join(OUT_DIR, "version.ts"),
  `${BANNER}\nexport const SCHEMA_VERSION = ${version} as const;\n`,
  { encoding: "utf8" },
);
console.log(`gen:types: ${files.length} schemas → ${OUT_DIR} (schema version ${version})`);
